export type Video = {
  id: string;
  title: string;
  category: string;
  description: string;
  thumbnail: string;
  videoUrl: string;
  speaker: string;
  teacherImage: string;
  userName: string;
  views: number;
  publishedAt: string;
};

export const videos: Video[] = [
  {
    id: "1",
    title: "Les bases de l’électricité",
    category: "Sciences",
    description: "Découvrez les principes de base de l’électricité.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/electricity.jpg",
    videoUrl: "https://www.youtube.com/embed/UEPVwBe4aD8",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "2",
    title: "Histoire de l’Égypte antique",
    category: "Histoire",
    description: "Plongez dans l’histoire fascinante de l’Égypte antique.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/egypt.jpg",
    videoUrl: "https://www.youtube.com/embed/FwO2OKBuP90",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "3",
    title: "Introduction à la programmation",
    category: "Informatique",
    description: "Apprenez les bases de la programmation en quelques minutes.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/programming.jpg",
    videoUrl: "https://www.youtube.com/embed/zOjov-2OZ0E",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "4",
    title: "Les fondamentaux des mathématiques",
    category: "Mathématiques",
    description: "Révisez les bases des mathématiques pour tous les niveaux.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/maths.jpg",
    videoUrl: "https://www.youtube.com/embed/K6ACzT6PCmM",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "5",
    title: "La Révolution française",
    category: "Histoire",
    description: "Une explication claire de la Révolution française.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/french-revolution.jpg",
    videoUrl: "https://www.youtube.com/embed/X-puDfbSSwY",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "6",
    title: "Comprendre le système solaire",
    category: "Astronomie",
    description: "Explorez le système solaire et ses planètes.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/solar-system.jpg",
    videoUrl: "https://www.youtube.com/embed/libKVRa01L8",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "7",
    title: "L’intelligence artificielle expliquée",
    category: "Technologie",
    description: "Introduction simple à l’intelligence artificielle.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/ai.jpg",
    videoUrl: "https://www.youtube.com/embed/2ePf9rue1Ao",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "8",
    title: "Bases de la physique quantique",
    category: "Physique",
    description: "Initiez-vous aux mystères de la physique quantique.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/quantum.jpg",
    videoUrl: "https://www.youtube.com/embed/Q1YqgPAtzho",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "9",
    title: "Les volcans : fonctionnement",
    category: "Géographie",
    description: "Découvrez comment fonctionnent les volcans.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/volcano.jpg",
    videoUrl: "https://www.youtube.com/embed/VNGUdObDoLk",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "10",
    title: "Comment fonctionne Internet ?",
    category: "Technologie",
    description: "Une explication simple d’Internet.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/internet.jpg",
    videoUrl: "https://www.youtube.com/embed/x3c1ih2NJEg",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "11",
    title: "Introduction à la biologie cellulaire",
    category: "Biologie",
    description: "Apprenez comment fonctionne la cellule.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/cell-biology.jpg",
    videoUrl: "https://www.youtube.com/embed/URUJD5NEXC8",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "12",
    title: "La démocratie expliquée",
    category: "Civisme",
    description: "Comprendre le fonctionnement d’un système démocratique.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/democracy.jpg",
    videoUrl: "https://www.youtube.com/embed/8gr5rIK097U",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "13",
    title: "Les bases de l’économie",
    category: "Économie",
    description: "Introduction aux concepts économiques clés.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/economy.jpg",
    videoUrl: "https://www.youtube.com/embed/3ez10ADR_gM",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "14",
    title: "Premiers secours : gestes qui sauvent",
    category: "Santé",
    description: "Apprenez les gestes essentiels de premiers secours.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/first-aid.jpg",
    videoUrl: "https://www.youtube.com/embed/1kSyGd4NQZQ",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "15",
    title: "Le réchauffement climatique",
    category: "Environnement",
    description: "Explication du changement climatique et ses conséquences.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/climate.jpg",
    videoUrl: "https://www.youtube.com/embed/EtW2rrLHs08",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "16",
    title: "Apprendre le HTML en 10 minutes",
    category: "Informatique",
    description: "Les bases du HTML pour débutants.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/html.jpg",
    videoUrl: "https://www.youtube.com/embed/qz0aGYrrlhU",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "17",
    title: "Histoire de la Seconde Guerre mondiale",
    category: "Histoire",
    description: "Résumé de la Seconde Guerre mondiale.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/ww2.jpg",
    videoUrl: "https://www.youtube.com/embed/UUg7pMi4N0I",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "18",
    title: "Comment faire une dissertation",
    category: "Méthodologie",
    description: "Les étapes clés pour réussir une dissertation.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/essay.jpg",
    videoUrl: "https://www.youtube.com/embed/PrO_XYoHiT4",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "19",
    title: "La photosynthèse",
    category: "Biologie",
    description: "Comprendre le processus de la photosynthèse.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/photosynthesis.jpg",
    videoUrl: "https://www.youtube.com/embed/LVvKjt2sda0",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
  {
    id: "20",
    title: "Apprendre le CSS en 10 minutes",
    category: "Informatique",
    description: "Découvrir le CSS rapidement et efficacement.",
    speaker: "Camille Durand",
    teacherImage: "Camille Nelson",
    thumbnail: "/images/css.jpg",
    videoUrl: "https://www.youtube.com/embed/OEV8gMkCHXQ",
    views: 12,
    userName: "august-dev",
    publishedAt: "3 mois",
  },
];
